// flow-typed signature: c003e1ddfd6eae122c5d6cee49272309
// flow-typed version: <<STUB>>/@openlattice/lattice-community-restorative-court_v0.6.3/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@openlattice/lattice-community-restorative-court'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@openlattice/lattice-community-restorative-court' {
  declare module.exports: any;
}
