// flow-typed signature: 38e0e2806559ff6b1f020d7c0dccb9d3
// flow-typed version: <<STUB>>/@openlattice/lattice-helpline-center_v0.2.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@openlattice/lattice-helpline-center'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@openlattice/lattice-helpline-center' {
  declare module.exports: any;
}
