// flow-typed signature: 71a1cea2dccfb9b7ce497326d82fdf71
// flow-typed version: <<STUB>>/fast-xml-parser_v3.17.4/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-xml-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-xml-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

declare module 'fast-xml-parser/src/json2xml' {
  declare module.exports: any;
}