// flow-typed signature: b2493b9655ad65ff1832821bd591031f
// flow-typed version: <<STUB>>/lattice-fabricate_v0.14.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-fabricate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-fabricate' {
  declare module.exports: any;
}
