// flow-typed signature: 32c8dc31953a860b2e7ce669513a3195
// flow-typed version: <<STUB>>/lattice_v^0.30.2/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lattice/build/lattice' {
  declare module.exports: any;
}

declare module 'lattice/build/lattice.min' {
  declare module.exports: any;
}

declare module 'lattice/config/env' {
  declare module.exports: any;
}

declare module 'lattice/config/flow/types' {
  declare module.exports: any;
}

declare module 'lattice/config/karma/karma.config.babel' {
  declare module.exports: any;
}

declare module 'lattice/config/karma/karma.config.base' {
  declare module.exports: any;
}

declare module 'lattice/config/karma/karma.config' {
  declare module.exports: any;
}

declare module 'lattice/config/lib.config' {
  declare module.exports: any;
}

declare module 'lattice/config/lib.paths' {
  declare module.exports: any;
}

declare module 'lattice/config/webpack/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AnalysisApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AuthorizationApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataSourcesApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/EntityDataModelApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/LinkingApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/OrganizationsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PermissionsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PrincipalsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/RequestsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/SearchApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/SyncApi' {
  declare module.exports: any;
}

declare module 'lattice/src/config/Configuration' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiNames' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiPaths' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/EnvToUrlMap' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/ActionTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/AnalyzerTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/index' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PermissionTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PrincipalTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/RequestStateTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/SecurableTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/index' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AccessCheck' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Ace' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Acl' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AclData' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AssociationType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/DataSource' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntitySet' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntityType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/FullyQualifiedName' {
  declare module.exports: any;
}

declare module 'lattice/src/models/index' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntitySet' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntityType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingRequest' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Organization' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Principal' {
  declare module.exports: any;
}

declare module 'lattice/src/models/PropertyType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Request' {
  declare module.exports: any;
}

declare module 'lattice/src/models/RequestStatus' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Role' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Schema' {
  declare module.exports: any;
}

declare module 'lattice/src/models/template' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/AxiosUtils' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/LangUtils' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/Logger' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/ValidationUtils' {
  declare module.exports: any;
}

declare module 'lattice/test/api/AuthorizationApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/DataApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/DataSourcesApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/EntityDataModelApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/LinkingApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/OrganizationsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/PermissionsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/PrincipalsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/RequestsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/api/SearchApi.test' {
  declare module.exports: any;
}

declare module 'lattice/test/config/Configuration.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/ActionTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/ApiNames.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/ApiPaths.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/EnvToUrlMap.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/InvalidParams' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/MockDataModels' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/PermissionTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/PrincipalTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/RequestStateTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/test/constants/SecurableTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/test/index.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/AccessCheck.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/Ace.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/Acl.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/AclData.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/DataSource.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/EntitySet.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/EntityType.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/FullyQualifiedName.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/index.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/LinkingEntitySet.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/LinkingEntityType.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/LinkingRequest.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/Organization.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/Principal.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/PropertyType.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/Request.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/RequestStatus.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/Role.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/Schema.test' {
  declare module.exports: any;
}

declare module 'lattice/test/models/template' {
  declare module.exports: any;
}

declare module 'lattice/test/TestSuite' {
  declare module.exports: any;
}

declare module 'lattice/test/utils/ApiTestUtils' {
  declare module.exports: any;
}

declare module 'lattice/test/utils/AxiosUtils.test' {
  declare module.exports: any;
}

declare module 'lattice/test/utils/MockDataUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lattice/build/lattice.js' {
  declare module.exports: $Exports<'lattice/build/lattice'>;
}
declare module 'lattice/build/lattice.min.js' {
  declare module.exports: $Exports<'lattice/build/lattice.min'>;
}
declare module 'lattice/config/env.js' {
  declare module.exports: $Exports<'lattice/config/env'>;
}
declare module 'lattice/config/flow/types.js' {
  declare module.exports: $Exports<'lattice/config/flow/types'>;
}
declare module 'lattice/config/karma/karma.config.babel.js' {
  declare module.exports: $Exports<'lattice/config/karma/karma.config.babel'>;
}
declare module 'lattice/config/karma/karma.config.base.js' {
  declare module.exports: $Exports<'lattice/config/karma/karma.config.base'>;
}
declare module 'lattice/config/karma/karma.config.js' {
  declare module.exports: $Exports<'lattice/config/karma/karma.config'>;
}
declare module 'lattice/config/lib.config.js' {
  declare module.exports: $Exports<'lattice/config/lib.config'>;
}
declare module 'lattice/config/lib.paths.js' {
  declare module.exports: $Exports<'lattice/config/lib.paths'>;
}
declare module 'lattice/config/webpack/webpack.config.babel.js' {
  declare module.exports: $Exports<'lattice/config/webpack/webpack.config.babel'>;
}
declare module 'lattice/src/api/AnalysisApi.js' {
  declare module.exports: $Exports<'lattice/src/api/AnalysisApi'>;
}
declare module 'lattice/src/api/AuthorizationApi.js' {
  declare module.exports: $Exports<'lattice/src/api/AuthorizationApi'>;
}
declare module 'lattice/src/api/DataApi.js' {
  declare module.exports: $Exports<'lattice/src/api/DataApi'>;
}
declare module 'lattice/src/api/DataSourcesApi.js' {
  declare module.exports: $Exports<'lattice/src/api/DataSourcesApi'>;
}
declare module 'lattice/src/api/EntityDataModelApi.js' {
  declare module.exports: $Exports<'lattice/src/api/EntityDataModelApi'>;
}
declare module 'lattice/src/api/LinkingApi.js' {
  declare module.exports: $Exports<'lattice/src/api/LinkingApi'>;
}
declare module 'lattice/src/api/OrganizationsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/OrganizationsApi'>;
}
declare module 'lattice/src/api/PermissionsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/PermissionsApi'>;
}
declare module 'lattice/src/api/PrincipalsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/PrincipalsApi'>;
}
declare module 'lattice/src/api/RequestsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/RequestsApi'>;
}
declare module 'lattice/src/api/SearchApi.js' {
  declare module.exports: $Exports<'lattice/src/api/SearchApi'>;
}
declare module 'lattice/src/api/SyncApi.js' {
  declare module.exports: $Exports<'lattice/src/api/SyncApi'>;
}
declare module 'lattice/src/config/Configuration.js' {
  declare module.exports: $Exports<'lattice/src/config/Configuration'>;
}
declare module 'lattice/src/constants/ApiNames.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiNames'>;
}
declare module 'lattice/src/constants/ApiPaths.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiPaths'>;
}
declare module 'lattice/src/constants/EnvToUrlMap.js' {
  declare module.exports: $Exports<'lattice/src/constants/EnvToUrlMap'>;
}
declare module 'lattice/src/constants/types/ActionTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/ActionTypes'>;
}
declare module 'lattice/src/constants/types/AnalyzerTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/AnalyzerTypes'>;
}
declare module 'lattice/src/constants/types/index.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/index'>;
}
declare module 'lattice/src/constants/types/PermissionTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PermissionTypes'>;
}
declare module 'lattice/src/constants/types/PrincipalTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PrincipalTypes'>;
}
declare module 'lattice/src/constants/types/RequestStateTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/RequestStateTypes'>;
}
declare module 'lattice/src/constants/types/SecurableTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/SecurableTypes'>;
}
declare module 'lattice/src/index.js' {
  declare module.exports: $Exports<'lattice/src/index'>;
}
declare module 'lattice/src/models/AccessCheck.js' {
  declare module.exports: $Exports<'lattice/src/models/AccessCheck'>;
}
declare module 'lattice/src/models/Ace.js' {
  declare module.exports: $Exports<'lattice/src/models/Ace'>;
}
declare module 'lattice/src/models/Acl.js' {
  declare module.exports: $Exports<'lattice/src/models/Acl'>;
}
declare module 'lattice/src/models/AclData.js' {
  declare module.exports: $Exports<'lattice/src/models/AclData'>;
}
declare module 'lattice/src/models/AssociationType.js' {
  declare module.exports: $Exports<'lattice/src/models/AssociationType'>;
}
declare module 'lattice/src/models/DataSource.js' {
  declare module.exports: $Exports<'lattice/src/models/DataSource'>;
}
declare module 'lattice/src/models/EntitySet.js' {
  declare module.exports: $Exports<'lattice/src/models/EntitySet'>;
}
declare module 'lattice/src/models/EntityType.js' {
  declare module.exports: $Exports<'lattice/src/models/EntityType'>;
}
declare module 'lattice/src/models/FullyQualifiedName.js' {
  declare module.exports: $Exports<'lattice/src/models/FullyQualifiedName'>;
}
declare module 'lattice/src/models/index.js' {
  declare module.exports: $Exports<'lattice/src/models/index'>;
}
declare module 'lattice/src/models/LinkingEntitySet.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntitySet'>;
}
declare module 'lattice/src/models/LinkingEntityType.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntityType'>;
}
declare module 'lattice/src/models/LinkingRequest.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingRequest'>;
}
declare module 'lattice/src/models/Organization.js' {
  declare module.exports: $Exports<'lattice/src/models/Organization'>;
}
declare module 'lattice/src/models/Principal.js' {
  declare module.exports: $Exports<'lattice/src/models/Principal'>;
}
declare module 'lattice/src/models/PropertyType.js' {
  declare module.exports: $Exports<'lattice/src/models/PropertyType'>;
}
declare module 'lattice/src/models/Request.js' {
  declare module.exports: $Exports<'lattice/src/models/Request'>;
}
declare module 'lattice/src/models/RequestStatus.js' {
  declare module.exports: $Exports<'lattice/src/models/RequestStatus'>;
}
declare module 'lattice/src/models/Role.js' {
  declare module.exports: $Exports<'lattice/src/models/Role'>;
}
declare module 'lattice/src/models/Schema.js' {
  declare module.exports: $Exports<'lattice/src/models/Schema'>;
}
declare module 'lattice/src/models/template.js' {
  declare module.exports: $Exports<'lattice/src/models/template'>;
}
declare module 'lattice/src/utils/AxiosUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/AxiosUtils'>;
}
declare module 'lattice/src/utils/LangUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/LangUtils'>;
}
declare module 'lattice/src/utils/Logger.js' {
  declare module.exports: $Exports<'lattice/src/utils/Logger'>;
}
declare module 'lattice/src/utils/ValidationUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/ValidationUtils'>;
}
declare module 'lattice/test/api/AuthorizationApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/AuthorizationApi.test'>;
}
declare module 'lattice/test/api/DataApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/DataApi.test'>;
}
declare module 'lattice/test/api/DataSourcesApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/DataSourcesApi.test'>;
}
declare module 'lattice/test/api/EntityDataModelApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/EntityDataModelApi.test'>;
}
declare module 'lattice/test/api/LinkingApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/LinkingApi.test'>;
}
declare module 'lattice/test/api/OrganizationsApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/OrganizationsApi.test'>;
}
declare module 'lattice/test/api/PermissionsApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/PermissionsApi.test'>;
}
declare module 'lattice/test/api/PrincipalsApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/PrincipalsApi.test'>;
}
declare module 'lattice/test/api/RequestsApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/RequestsApi.test'>;
}
declare module 'lattice/test/api/SearchApi.test.js' {
  declare module.exports: $Exports<'lattice/test/api/SearchApi.test'>;
}
declare module 'lattice/test/config/Configuration.test.js' {
  declare module.exports: $Exports<'lattice/test/config/Configuration.test'>;
}
declare module 'lattice/test/constants/ActionTypes.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/ActionTypes.test'>;
}
declare module 'lattice/test/constants/ApiNames.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/ApiNames.test'>;
}
declare module 'lattice/test/constants/ApiPaths.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/ApiPaths.test'>;
}
declare module 'lattice/test/constants/EnvToUrlMap.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/EnvToUrlMap.test'>;
}
declare module 'lattice/test/constants/InvalidParams.js' {
  declare module.exports: $Exports<'lattice/test/constants/InvalidParams'>;
}
declare module 'lattice/test/constants/MockDataModels.js' {
  declare module.exports: $Exports<'lattice/test/constants/MockDataModels'>;
}
declare module 'lattice/test/constants/PermissionTypes.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/PermissionTypes.test'>;
}
declare module 'lattice/test/constants/PrincipalTypes.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/PrincipalTypes.test'>;
}
declare module 'lattice/test/constants/RequestStateTypes.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/RequestStateTypes.test'>;
}
declare module 'lattice/test/constants/SecurableTypes.test.js' {
  declare module.exports: $Exports<'lattice/test/constants/SecurableTypes.test'>;
}
declare module 'lattice/test/index.test.js' {
  declare module.exports: $Exports<'lattice/test/index.test'>;
}
declare module 'lattice/test/models/AccessCheck.test.js' {
  declare module.exports: $Exports<'lattice/test/models/AccessCheck.test'>;
}
declare module 'lattice/test/models/Ace.test.js' {
  declare module.exports: $Exports<'lattice/test/models/Ace.test'>;
}
declare module 'lattice/test/models/Acl.test.js' {
  declare module.exports: $Exports<'lattice/test/models/Acl.test'>;
}
declare module 'lattice/test/models/AclData.test.js' {
  declare module.exports: $Exports<'lattice/test/models/AclData.test'>;
}
declare module 'lattice/test/models/DataSource.test.js' {
  declare module.exports: $Exports<'lattice/test/models/DataSource.test'>;
}
declare module 'lattice/test/models/EntitySet.test.js' {
  declare module.exports: $Exports<'lattice/test/models/EntitySet.test'>;
}
declare module 'lattice/test/models/EntityType.test.js' {
  declare module.exports: $Exports<'lattice/test/models/EntityType.test'>;
}
declare module 'lattice/test/models/FullyQualifiedName.test.js' {
  declare module.exports: $Exports<'lattice/test/models/FullyQualifiedName.test'>;
}
declare module 'lattice/test/models/index.test.js' {
  declare module.exports: $Exports<'lattice/test/models/index.test'>;
}
declare module 'lattice/test/models/LinkingEntitySet.test.js' {
  declare module.exports: $Exports<'lattice/test/models/LinkingEntitySet.test'>;
}
declare module 'lattice/test/models/LinkingEntityType.test.js' {
  declare module.exports: $Exports<'lattice/test/models/LinkingEntityType.test'>;
}
declare module 'lattice/test/models/LinkingRequest.test.js' {
  declare module.exports: $Exports<'lattice/test/models/LinkingRequest.test'>;
}
declare module 'lattice/test/models/Organization.test.js' {
  declare module.exports: $Exports<'lattice/test/models/Organization.test'>;
}
declare module 'lattice/test/models/Principal.test.js' {
  declare module.exports: $Exports<'lattice/test/models/Principal.test'>;
}
declare module 'lattice/test/models/PropertyType.test.js' {
  declare module.exports: $Exports<'lattice/test/models/PropertyType.test'>;
}
declare module 'lattice/test/models/Request.test.js' {
  declare module.exports: $Exports<'lattice/test/models/Request.test'>;
}
declare module 'lattice/test/models/RequestStatus.test.js' {
  declare module.exports: $Exports<'lattice/test/models/RequestStatus.test'>;
}
declare module 'lattice/test/models/Role.test.js' {
  declare module.exports: $Exports<'lattice/test/models/Role.test'>;
}
declare module 'lattice/test/models/Schema.test.js' {
  declare module.exports: $Exports<'lattice/test/models/Schema.test'>;
}
declare module 'lattice/test/models/template.js' {
  declare module.exports: $Exports<'lattice/test/models/template'>;
}
declare module 'lattice/test/TestSuite.js' {
  declare module.exports: $Exports<'lattice/test/TestSuite'>;
}
declare module 'lattice/test/utils/ApiTestUtils.js' {
  declare module.exports: $Exports<'lattice/test/utils/ApiTestUtils'>;
}
declare module 'lattice/test/utils/AxiosUtils.test.js' {
  declare module.exports: $Exports<'lattice/test/utils/AxiosUtils.test'>;
}
declare module 'lattice/test/utils/MockDataUtils.js' {
  declare module.exports: $Exports<'lattice/test/utils/MockDataUtils'>;
}
