// flow-typed signature: ba71088566f8cf94f4ba7ae02eda7f51
// flow-typed version: <<STUB>>/react-monaco-editor_v0.45.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-monaco-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-monaco-editor' {
  declare module.exports: any;
}
