// flow-typed signature: c68094c7f76f52f2bfb4d0d5dccf9adf
// flow-typed version: <<STUB>>/react-bootstrap-time-picker_v^1.0.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap-time-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap-time-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap-time-picker/dist/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap-time-picker/dist/bundle.js' {
  declare module.exports: $Exports<'react-bootstrap-time-picker/dist/bundle'>;
}
