// flow-typed signature: 133920d094c3711b8c1e4d242a1bcf8c
// flow-typed version: <<STUB>>/react-dropzone_v11.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}
